#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GenkNew")]
	public partial class DemoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBantin(Bantin instance);
    partial void UpdateBantin(Bantin instance);
    partial void DeleteBantin(Bantin instance);
    partial void InsertChiTiet(ChiTiet instance);
    partial void UpdateChiTiet(ChiTiet instance);
    partial void DeleteChiTiet(ChiTiet instance);
    partial void InsertDangNhap(DangNhap instance);
    partial void UpdateDangNhap(DangNhap instance);
    partial void DeleteDangNhap(DangNhap instance);
    #endregion
		
		public DemoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GenkNewConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DemoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bantin> Bantins
		{
			get
			{
				return this.GetTable<Bantin>();
			}
		}
		
		public System.Data.Linq.Table<ChiTiet> ChiTiets
		{
			get
			{
				return this.GetTable<ChiTiet>();
			}
		}
		
		public System.Data.Linq.Table<DangNhap> DangNhaps
		{
			get
			{
				return this.GetTable<DangNhap>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Bantin_Selectid")]
		public ISingleResult<Bantin_SelectidResult> Bantin_Selectid([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idbantin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idbantin);
			return ((ISingleResult<Bantin_SelectidResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Bantin_Delete")]
		public int Bantin_Delete([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDBanTin", DbType="Int")] System.Nullable<int> iDBanTin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iDBanTin);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Bantin_Insert")]
		public int Bantin_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string noiDung)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), noiDung);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Bantin_SelectAll")]
		public ISingleResult<Bantin_SelectAllResult> Bantin_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Bantin_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTiet_Insert")]
		public int ChiTiet_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tieude, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string noidung, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaydang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string mota, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string img, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDbantin", DbType="Int")] System.Nullable<int> iDbantin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tieude, noidung, ngaydang, mota, img, iDbantin);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Bantin_Update")]
		public int Bantin_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string noiDung, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IDBanTin", DbType="Int")] System.Nullable<int> iDBanTin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), noiDung, iDBanTin);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.chitiet_lanxem")]
		public int chitiet_lanxem([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> lanxem)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, lanxem);
			lanxem = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTiet_SelectAll")]
		public ISingleResult<ChiTiet_SelectAllResult> ChiTiet_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ChiTiet_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTiet_Select")]
		public ISingleResult<ChiTiet_SelectResult> ChiTiet_Select([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<ChiTiet_SelectResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Chitiet_Selectbantin")]
		public ISingleResult<Chitiet_SelectbantinResult> Chitiet_Selectbantin([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idbantin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idbantin);
			return ((ISingleResult<Chitiet_SelectbantinResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTiet_SelectID")]
		public ISingleResult<ChiTiet_SelectIDResult> ChiTiet_SelectID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((ISingleResult<ChiTiet_SelectIDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Chitiet_Selectradom")]
		public ISingleResult<Chitiet_SelectradomResult> Chitiet_Selectradom()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Chitiet_SelectradomResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Chitiet_SelectHome")]
		public ISingleResult<Chitiet_SelectHomeResult> Chitiet_SelectHome()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<Chitiet_SelectHomeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_Insert1")]
		public int DangNhap_Insert1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fullname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string passWord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fullname, ngaysinh, userName, passWord);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTiet_Update")]
		public int ChiTiet_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tieude, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string noidung, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaydang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string mota, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string img, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tieude, noidung, ngaydang, mota, img, iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChiTiet_SLX")]
		public int ChiTiet_SLX([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> lanxem, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), lanxem, iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_Update", IsComposable=true)]
		public object DangNhap_Update([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string passWord)
		{
			return ((object)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idname, userName, passWord).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_Insert3")]
		public int DangNhap_Insert3([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string fullname, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string passWord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fullname, ngaysinh, userName, passWord);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_Search")]
		public ISingleResult<DangNhap_SearchResult> DangNhap_Search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string passWord)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, passWord);
			return ((ISingleResult<DangNhap_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_SelectAll")]
		public ISingleResult<DangNhap_SelectAllResult> DangNhap_SelectAll()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<DangNhap_SelectAllResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_Acount_Login")]
		public ISingleResult<Sp_Acount_LoginResult> Sp_Acount_Login([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password);
			return ((ISingleResult<Sp_Acount_LoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.test")]
		public int test([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string keysearch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, keysearch);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.test2")]
		public int test2([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string keysearch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keysearch);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.test4")]
		public ISingleResult<test4Result> test4([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string keysearch)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keysearch);
			return ((ISingleResult<test4Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.test3")]
		public int test3([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(MAX)")] string keysearch, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idbantin)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), keysearch, idbantin);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Timkiem_tieude")]
		public ISingleResult<Timkiem_tieudeResult> Timkiem_tieude([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(200)")] string tieude)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tieude);
			return ((ISingleResult<Timkiem_tieudeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.hotnew")]
		public ISingleResult<hotnewResult> hotnew()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<hotnewResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.radom1")]
		public ISingleResult<radom1Result> radom1()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<radom1Result>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bantin")]
	public partial class Bantin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDBantin;
		
		private string _noidung;
		
		private EntitySet<ChiTiet> _ChiTiets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBantinChanging(int value);
    partial void OnIDBantinChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    #endregion
		
		public Bantin()
		{
			this._ChiTiets = new EntitySet<ChiTiet>(new Action<ChiTiet>(this.attach_ChiTiets), new Action<ChiTiet>(this.detach_ChiTiets));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBantin", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IDBantin
		{
			get
			{
				return this._IDBantin;
			}
			set
			{
				if ((this._IDBantin != value))
				{
					this.OnIDBantinChanging(value);
					this.SendPropertyChanging();
					this._IDBantin = value;
					this.SendPropertyChanged("IDBantin");
					this.OnIDBantinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(50)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bantin_ChiTiet", Storage="_ChiTiets", ThisKey="IDBantin", OtherKey="IDbantin")]
		public EntitySet<ChiTiet> ChiTiets
		{
			get
			{
				return this._ChiTiets;
			}
			set
			{
				this._ChiTiets.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTiets(ChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.Bantin = this;
		}
		
		private void detach_ChiTiets(ChiTiet entity)
		{
			this.SendPropertyChanging();
			entity.Bantin = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTiet")]
	public partial class ChiTiet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		private EntityRef<Bantin> _Bantin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OntieudeChanging(string value);
    partial void OntieudeChanged();
    partial void OnnoidungChanging(string value);
    partial void OnnoidungChanged();
    partial void OnlanxemChanging(System.Nullable<int> value);
    partial void OnlanxemChanged();
    partial void OnngaydangtinChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydangtinChanged();
    partial void OnmotaChanging(string value);
    partial void OnmotaChanged();
    partial void OnimgChanging(string value);
    partial void OnimgChanged();
    partial void OnIDbantinChanging(int value);
    partial void OnIDbantinChanged();
    #endregion
		
		public ChiTiet()
		{
			this._Bantin = default(EntityRef<Bantin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this.OntieudeChanging(value);
					this.SendPropertyChanging();
					this._tieude = value;
					this.SendPropertyChanged("tieude");
					this.OntieudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this.OnnoidungChanging(value);
					this.SendPropertyChanging();
					this._noidung = value;
					this.SendPropertyChanged("noidung");
					this.OnnoidungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this.OnlanxemChanging(value);
					this.SendPropertyChanging();
					this._lanxem = value;
					this.SendPropertyChanged("lanxem");
					this.OnlanxemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this.OnngaydangtinChanging(value);
					this.SendPropertyChanging();
					this._ngaydangtin = value;
					this.SendPropertyChanged("ngaydangtin");
					this.OnngaydangtinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this.OnmotaChanging(value);
					this.SendPropertyChanging();
					this._mota = value;
					this.SendPropertyChanged("mota");
					this.OnmotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this.OnimgChanging(value);
					this.SendPropertyChanging();
					this._img = value;
					this.SendPropertyChanged("img");
					this.OnimgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					if (this._Bantin.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDbantinChanging(value);
					this.SendPropertyChanging();
					this._IDbantin = value;
					this.SendPropertyChanged("IDbantin");
					this.OnIDbantinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Bantin_ChiTiet", Storage="_Bantin", ThisKey="IDbantin", OtherKey="IDBantin", IsForeignKey=true)]
		public Bantin Bantin
		{
			get
			{
				return this._Bantin.Entity;
			}
			set
			{
				Bantin previousValue = this._Bantin.Entity;
				if (((previousValue != value) 
							|| (this._Bantin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Bantin.Entity = null;
						previousValue.ChiTiets.Remove(this);
					}
					this._Bantin.Entity = value;
					if ((value != null))
					{
						value.ChiTiets.Add(this);
						this._IDbantin = value.IDBantin;
					}
					else
					{
						this._IDbantin = default(int);
					}
					this.SendPropertyChanged("Bantin");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap")]
	public partial class DangNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDname;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private string _ngaythangnamsinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDnameChanging(int value);
    partial void OnIDnameChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnngaythangnamsinhChanging(string value);
    partial void OnngaythangnamsinhChanged();
    #endregion
		
		public DangNhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDname", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDname
		{
			get
			{
				return this._IDname;
			}
			set
			{
				if ((this._IDname != value))
				{
					this.OnIDnameChanging(value);
					this.SendPropertyChanging();
					this._IDname = value;
					this.SendPropertyChanged("IDname");
					this.OnIDnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(50)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this.OnfullnameChanging(value);
					this.SendPropertyChanging();
					this._fullname = value;
					this.SendPropertyChanged("fullname");
					this.OnfullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythangnamsinh", DbType="NVarChar(50)")]
		public string ngaythangnamsinh
		{
			get
			{
				return this._ngaythangnamsinh;
			}
			set
			{
				if ((this._ngaythangnamsinh != value))
				{
					this.OnngaythangnamsinhChanging(value);
					this.SendPropertyChanging();
					this._ngaythangnamsinh = value;
					this.SendPropertyChanged("ngaythangnamsinh");
					this.OnngaythangnamsinhChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class Bantin_SelectidResult
	{
		
		private int _IDBantin;
		
		private string _noidung;
		
		public Bantin_SelectidResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBantin", DbType="Int NOT NULL")]
		public int IDBantin
		{
			get
			{
				return this._IDBantin;
			}
			set
			{
				if ((this._IDBantin != value))
				{
					this._IDBantin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(50)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
	}
	
	public partial class Bantin_SelectAllResult
	{
		
		private int _IDBantin;
		
		private string _noidung;
		
		public Bantin_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBantin", DbType="Int NOT NULL")]
		public int IDBantin
		{
			get
			{
				return this._IDBantin;
			}
			set
			{
				if ((this._IDBantin != value))
				{
					this._IDBantin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(50)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
	}
	
	public partial class ChiTiet_SelectAllResult
	{
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		public ChiTiet_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this._lanxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this._ngaydangtin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					this._IDbantin = value;
				}
			}
		}
	}
	
	public partial class ChiTiet_SelectResult
	{
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		public ChiTiet_SelectResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this._lanxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this._ngaydangtin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					this._IDbantin = value;
				}
			}
		}
	}
	
	public partial class Chitiet_SelectbantinResult
	{
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		public Chitiet_SelectbantinResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this._lanxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this._ngaydangtin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					this._IDbantin = value;
				}
			}
		}
	}
	
	public partial class ChiTiet_SelectIDResult
	{
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		public ChiTiet_SelectIDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this._lanxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this._ngaydangtin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					this._IDbantin = value;
				}
			}
		}
	}
	
	public partial class Chitiet_SelectradomResult
	{
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		public Chitiet_SelectradomResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this._lanxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this._ngaydangtin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					this._IDbantin = value;
				}
			}
		}
	}
	
	public partial class Chitiet_SelectHomeResult
	{
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		public Chitiet_SelectHomeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this._lanxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this._ngaydangtin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					this._IDbantin = value;
				}
			}
		}
	}
	
	public partial class DangNhap_SearchResult
	{
		
		private int _IDname;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private string _ngaythangnamsinh;
		
		public DangNhap_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDname", DbType="Int NOT NULL")]
		public int IDname
		{
			get
			{
				return this._IDname;
			}
			set
			{
				if ((this._IDname != value))
				{
					this._IDname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(50)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this._fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythangnamsinh", DbType="NVarChar(50)")]
		public string ngaythangnamsinh
		{
			get
			{
				return this._ngaythangnamsinh;
			}
			set
			{
				if ((this._ngaythangnamsinh != value))
				{
					this._ngaythangnamsinh = value;
				}
			}
		}
	}
	
	public partial class DangNhap_SelectAllResult
	{
		
		private int _IDname;
		
		private string _username;
		
		private string _password;
		
		private string _fullname;
		
		private string _ngaythangnamsinh;
		
		public DangNhap_SelectAllResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDname", DbType="Int NOT NULL")]
		public int IDname
		{
			get
			{
				return this._IDname;
			}
			set
			{
				if ((this._IDname != value))
				{
					this._IDname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(50)")]
		public string fullname
		{
			get
			{
				return this._fullname;
			}
			set
			{
				if ((this._fullname != value))
				{
					this._fullname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythangnamsinh", DbType="NVarChar(50)")]
		public string ngaythangnamsinh
		{
			get
			{
				return this._ngaythangnamsinh;
			}
			set
			{
				if ((this._ngaythangnamsinh != value))
				{
					this._ngaythangnamsinh = value;
				}
			}
		}
	}
	
	public partial class Sp_Acount_LoginResult
	{
		
		private System.Nullable<bool> _Column1;
		
		public Sp_Acount_LoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Bit")]
		public System.Nullable<bool> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class test4Result
	{
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		public test4Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this._lanxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this._ngaydangtin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					this._IDbantin = value;
				}
			}
		}
	}
	
	public partial class Timkiem_tieudeResult
	{
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		public Timkiem_tieudeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this._lanxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this._ngaydangtin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					this._IDbantin = value;
				}
			}
		}
	}
	
	public partial class hotnewResult
	{
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		public hotnewResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this._lanxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this._ngaydangtin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					this._IDbantin = value;
				}
			}
		}
	}
	
	public partial class radom1Result
	{
		
		private int _ID;
		
		private string _tieude;
		
		private string _noidung;
		
		private System.Nullable<int> _lanxem;
		
		private System.Nullable<System.DateTime> _ngaydangtin;
		
		private string _mota;
		
		private string _img;
		
		private int _IDbantin;
		
		public radom1Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tieude", DbType="NVarChar(200)")]
		public string tieude
		{
			get
			{
				return this._tieude;
			}
			set
			{
				if ((this._tieude != value))
				{
					this._tieude = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_noidung", DbType="NVarChar(MAX)")]
		public string noidung
		{
			get
			{
				return this._noidung;
			}
			set
			{
				if ((this._noidung != value))
				{
					this._noidung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lanxem", DbType="Int")]
		public System.Nullable<int> lanxem
		{
			get
			{
				return this._lanxem;
			}
			set
			{
				if ((this._lanxem != value))
				{
					this._lanxem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydangtin", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydangtin
		{
			get
			{
				return this._ngaydangtin;
			}
			set
			{
				if ((this._ngaydangtin != value))
				{
					this._ngaydangtin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mota", DbType="NVarChar(MAX)")]
		public string mota
		{
			get
			{
				return this._mota;
			}
			set
			{
				if ((this._mota != value))
				{
					this._mota = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_img", DbType="NVarChar(MAX)")]
		public string img
		{
			get
			{
				return this._img;
			}
			set
			{
				if ((this._img != value))
				{
					this._img = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDbantin", DbType="Int NOT NULL")]
		public int IDbantin
		{
			get
			{
				return this._IDbantin;
			}
			set
			{
				if ((this._IDbantin != value))
				{
					this._IDbantin = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
